Us 67 vu
TamerlanHuseynov/vytrackAutomation pull request #3
Opened 2022-03-09 08:21 UTC by vupham129

Please review my codes for US67.

2022-03-09 10:22 UTC, TamerlanHuseynov requested changes
Your code looks good besides the data provider. It has long lines which can be written in a shorter way. I have put comments on the exact code lines that have to be changed. Please review your code again and don't hesitate to ask questions.

2022-03-09 10:22 UTC, TamerlanHuseynov commented on src/test/java/com/vytrack/test/US_67.java
> +                {ConfigurationReader.getProperty("usernameSalesManager4"), ConfigurationReader.getProperty("password")}
You can just write here keywords without calling and Configuration Reader get Property. And password also can be written as keyword.

2022-03-09 10:22 UTC, TamerlanHuseynov commented on src/test/java/com/vytrack/test/US_67.java
> +        VyTrack_Login.login(Driver.getDriver(), username, password);
And here you can import Configuration Reader get property for username and password. Every time it is gonna take data provider keys and return their value for you.

2022-03-09 15:16 UTC, vupham129 commented on src/test/java/com/vytrack/test/US_67.java
> +                {ConfigurationReader.getProperty("usernameSalesManager4"), ConfigurationReader.getProperty("password")}
okie. i will take a look and fix it

2022-03-09 15:51 UTC, vupham129 commented on src/test/java/com/vytrack/test/US_67.java
> +        VyTrack_Login.login(Driver.getDriver(), username, password);
fixed, Please take a look :)

2022-03-09 16:38 UTC, MohammedAlshalchi approved these changes
It looks good codes but as Aaron said you can use one credential for each

2022-03-10 01:23 UTC, TamerlanHuseynov approved these changes
Well done! It seems you have time to  pick another  not assigned US and work on it :)

2022-03-10 07:56 UTC, vupham129 commented
@TamerlanHuseynov I can take Azaman's US to work on.

2022-03-10 08:05 UTC, vupham129 commented
@TamerlanHuseynov I'll work on Maurice's US

2022-03-12 01:04 UTC, Linderwow approved these changes
Great Job. Keep up the good work.

2022-03-12 01:04 UTC, KatiU approved these changes
Great job.Good work.

2022-03-12 01:04 UTC, merged